name: XenoTransfer
author: Xenophilicy
version: 2.1.0
description: Lets you transfer between your server network with forms!
main: XenoTransfer\XenoTransfer
api: 3.0.0
commands:
 servers:
  description: See your servers!
  permission: xenotransfer.use.servers
 xenotransfer:
  description: About the plugin XenoTransfer!
  permission: xenotransfer.use.serversabt
permissions:
 xenotransfer.use.servers:
  default: true
 xenotransfer.use.serversabt:
  default: true
