#MADE BY:
# __    __                                          __        __  __  __                     
#/  |  /  |                                        /  |      /  |/  |/  |                    
#$$ |  $$ |  ______   _______    ______    ______  $$ |____  $$/ $$ |$$/   _______  __    __ 
#$$  \/$$/  /      \ /       \  /      \  /      \ $$      \ /  |$$ |/  | /       |/  |  /  |
# $$  $$<  /$$$$$$  |$$$$$$$  |/$$$$$$  |/$$$$$$  |$$$$$$$  |$$ |$$ |$$ |/$$$$$$$/ $$ |  $$ |
#  $$$$  \ $$    $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |$$ |$$ |$$ |      $$ |  $$ |
#$$ /$$  |$$$$$$$$/ $$ |  $$ |$$ \__$$ |$$ |__$$ |$$ |  $$ |$$ |$$ |$$ |$$ \_____ $$ \__$$ |#
#$$ |  $$ |$$       |$$ |  $$ |$$    $$/ $$    $$/ $$ |  $$ |$$ |$$ |$$ |$$       |$$    $$ |
#$$/   $$/  $$$$$$$/ $$/   $$/  $$$$$$/  $$$$$$$/  $$/   $$/ $$/ $$/ $$/  $$$$$$$/  $$$$$$$ |
#                                        $$ |                                      /  \__$$ |
#                                        $$ |                                      $$    $$/ 
#                                        $$/                                        $$$$$$/  

#Message displayed when the plugin loads (after the default)
Enable_Message: "§6Xenophilicy §ahas made the plugin successfully!"

#Message displayed when the plugin loads (after the default)
Disable_Message: "§6Xenophilicy §ahas made the plugin successfully again!"

#-----------------------------------------------------------------------
#First Server
Server_1_Label: "§6Lobby"
Server_1_IP: "xenoservers.ddns.net"
Server_1_Port: "19132"
#-----------------------------------------------------------------------
#Second Server
Server_2_Label: "§2Prison"
Server_2_IP: "xenoservers.ddns.net"
Server_2_Port: "19133"
#-----------------------------------------------------------------------
#Third Server
Server_3_Label: "§5Creative"
Server_3_IP: "xenoservers.ddns.net"
Server_3_Port: "19134"
#-----------------------------------------------------------------------
#Fourth Server
Server_4_Label: "§4PvP"
Server_4_IP: "xenoservers.ddns.net"
Server_4_Port: "19135"
#-----------------------------------------------------------------------
#Fifth Server
Server_5_Label: "§3Sky§cBlock"
Server_5_IP: "xenoservers.ddns.net"
Server_5_Port: "19136"
#-----------------------------------------------------------------------