# MADE BY:
#  __    __                                          __        __  __  __                     
# /  |  /  |                                        /  |      /  |/  |/  |                    
# $$ |  $$ |  ______   _______    ______    ______  $$ |____  $$/ $$ |$$/   _______  __    __ 
# $$  \/$$/  /      \ /       \  /      \  /      \ $$      \ /  |$$ |/  | /       |/  |  /  |
#  $$  $$<  /$$$$$$  |$$$$$$$  |/$$$$$$  |/$$$$$$  |$$$$$$$  |$$ |$$ |$$ |/$$$$$$$/ $$ |  $$ |
#   $$$$  \ $$    $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |$$ |$$ |$$ |      $$ |  $$ |
#  $$ /$$  |$$$$$$$$/ $$ |  $$ |$$ \__$$ |$$ |__$$ |$$ |  $$ |$$ |$$ |$$ |$$ \_____ $$ \__$$ |
# $$ |  $$ |$$       |$$ |  $$ |$$    $$/ $$    $$/ $$ |  $$ |$$ |$$ |$$ |$$       |$$    $$ |
# $$/   $$/  $$$$$$$/ $$/   $$/  $$$$$$/  $$$$$$$/  $$/   $$/ $$/ $$/ $$/  $$$$$$$/  $$$$$$$ |
#                                         $$ |                                      /  \__$$ |
#                                         $$ |                                      $$    $$/ 
#                                         $$/                                        $$$$$$/       
# EDITED BY:
#
#            /$$   /$$                                        
#           | $$  /$$/                                        
#   /$$$$$$ | $$ /$$/   /$$$$$$  /$$$$$$$$  /$$$$$$  /$$$$$$$ 
#  /$$__  $$| $$$$$/   /$$__  $$|____ /$$/ |____  $$| $$__  $$
# | $$  \ $$| $$  $$  | $$  \ $$   /$$$$/   /$$$$$$$| $$  \ $$
# | $$  | $$| $$\  $$ | $$  | $$  /$$__/   /$$__  $$| $$  | $$
# |  $$$$$$/| $$ \  $$|  $$$$$$$ /$$$$$$$$|  $$$$$$$| $$  | $$
#  \______/ |__/  \__/ \____  $$|________/ \_______/|__/  |__/
#                           | $$                              
#                           | $$                              
#                           |__/  


# Choose whether the selector item should be enabled
Selector-Support: true

# Choose what item the server selector should be
Selector-Item: 345

# Selector Name → Text that will show on the selector in the player's inventory!
Selector-Name: "§l§aServer Selector"

# This is the title of the server UI
UI-Title: "§9Server List"

# This is the message the will show under your title on the server UI
UI-Message: "§aChoose a server to transfer to!"

# You can set any server to false to disable them inside the UI! (Make sure to leave at least one)
# You can also use '§' on the labels to colorize your servers inside the UI!

Server-1:
  Label: "§6§lLobby Server" 
  IP: "xenoservers.ddns.net" 
  Port: "19132" 

Server-2:
  Label: "§2§lPrison Server" 
  IP: "xenoservers.ddns.net"
  Port: "19133" 

Server-3:
  Label: "§5§lCreative Server" 
  IP: "xenoservers.ddns.net"
  Port: "19134" 

Server-4:
  Label: "§4§lPvP Server" 
  IP: "xenoservers.ddns.net"
  Port: "19135" 

Server-5:
  Label: false
  IP: false
  Port: false
