# MADE BY:
# __    __                                          __        __  __  __                     
#/  |  /  |                                        /  |      /  |/  |/  |                    
#$$ |  $$ |  ______   _______    ______    ______  $$ |____  $$/ $$ |$$/   _______  __    __ 
#$$  \/$$/  /      \ /       \  /      \  /      \ $$      \ /  |$$ |/  | /       |/  |  /  |
# $$  $$<  /$$$$$$  |$$$$$$$  |/$$$$$$  |/$$$$$$  |$$$$$$$  |$$ |$$ |$$ |/$$$$$$$/ $$ |  $$ |
#  $$$$  \ $$    $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |$$ |$$ |$$ |      $$ |  $$ |
# $$ /$$  |$$$$$$$$/ $$ |  $$ |$$ \__$$ |$$ |__$$ |$$ |  $$ |$$ |$$ |$$ |$$ \_____ $$ \__$$ |
#$$ |  $$ |$$       |$$ |  $$ |$$    $$/ $$    $$/ $$ |  $$ |$$ |$$ |$$ |$$       |$$    $$ |
#$$/   $$/  $$$$$$$/ $$/   $$/  $$$$$$/  $$$$$$$/  $$/   $$/ $$/ $$/ $$/  $$$$$$$/  $$$$$$$ |
#                                        $$ |                                      /  \__$$ |
#                                        $$ |                                      $$    $$/ 
#                                        $$/                                        $$$$$$/           
# Editied By:
#
#           /$$   /$$                                        
#          | $$  /$$/                                        
#  /$$$$$$ | $$ /$$/   /$$$$$$  /$$$$$$$$  /$$$$$$  /$$$$$$$ 
# /$$__  $$| $$$$$/   /$$__  $$|____ /$$/ |____  $$| $$__  $$
#| $$  \ $$| $$  $$  | $$  \ $$   /$$$$/   /$$$$$$$| $$  \ $$
#| $$  | $$| $$\  $$ | $$  | $$  /$$__/   /$$__  $$| $$  | $$
#|  $$$$$$/| $$ \  $$|  $$$$$$$ /$$$$$$$$|  $$$$$$$| $$  | $$
# \______/ |__/  \__/ \____  $$|________/ \_______/|__/  |__/
#                          | $$                              
#                          | $$                              
#                          |__/  



Compass-Name: "Server Selector"

#-------------------------- First Server ---------------------------

# Server Name → Custom text to be displayed on the button!
Server_1_Label: "§6§lLobby Server"

# Server IP → Write down your server's IP address!
Server_1_IP: "xenoservers.ddns.net"

# Server Port → Write down your server's Port!
Server_1_Port: "19132"

# Same steps apply to the other servers! (Set any server, but the first one, to false to disable them inside the UI)

#--------------------------- Second Server -------------------------

Server_2_Label: "§2§lPrison Server"

Server_2_IP: "xenoservers.ddns.net"

Server_2_Port: "19133"

#-------------------------- Third Server ---------------------------

Server_3_Label: "§5§lCreative Server"
 
Server_3_IP: "xenoservers.ddns.net"
 
Server_3_Port: "19134"

#-------------------------- Fourth Server --------------------------
 
Server_4_Label: "§4§lPvP Server"
 
Server_4_IP: "xenoservers.ddns.net"

Server_4_Port: "19135"

#-------------------------- Fifth Server --------------------------

Server_5_Label: false

Server_5_IP: false

Server_5_Port: false

#-----------------------------------------------------------------
